CREATE TABLE IF NOT EXISTS CUSTOMER (
  CUSTOMER_EYECATCHER VARCHAR(4),
  CUSTOMER_SORTCODE CHAR(6) NOT NULL,
  CUSTOMER_NUMBER CHAR(10) NOT NULL,
  CUSTOMER_TITLE VARCHAR(10),
  CUSTOMER_FIRST_NAME VARCHAR(50),
  CUSTOMER_LAST_NAME VARCHAR(50),
  CUSTOMER_DATE_OF_BIRTH INTEGER,
  CUSTOMER_PHONE VARCHAR(20),
  CUSTOMER_ADDR_LINE1 VARCHAR(50),
  CUSTOMER_ADDR_LINE2 VARCHAR(50),
  CUSTOMER_CITY VARCHAR(50),
  CUSTOMER_POSTCODE VARCHAR(10),
  CUSTOMER_COUNTRY VARCHAR(50),
  CUSTOMER_STATUS VARCHAR(10),
  CUSTOMER_CREATED_DATE INTEGER,
  CUSTOMER_CREDIT_SCORE INTEGER,
  CUSTOMER_CS_REVIEW_DATE INTEGER,
  PRIMARY KEY (CUSTOMER_SORTCODE, CUSTOMER_NUMBER)
);

CREATE TABLE IF NOT EXISTS ACCOUNT (
  ACCOUNT_EYECATCHER VARCHAR(8),
  ACCOUNT_CUSTOMER_NUMBER CHAR(10) NOT NULL,
  ACCOUNT_SORTCODE CHAR(6) NOT NULL,
  ACCOUNT_NUMBER CHAR(8) NOT NULL,
  ACCOUNT_TYPE VARCHAR(3),
  ACCOUNT_INTEREST_RATE DECIMAL(8,2),
  ACCOUNT_OPENED INTEGER,
  ACCOUNT_OVERDRAFT_LIMIT INTEGER,
  ACCOUNT_LAST_STATEMENT INTEGER,
  ACCOUNT_NEXT_STATEMENT INTEGER,
  ACCOUNT_AVAILABLE_BALANCE DECIMAL(15,2),
  ACCOUNT_ACTUAL_BALANCE DECIMAL(15,2),
  PRIMARY KEY (ACCOUNT_SORTCODE, ACCOUNT_NUMBER)
);

CREATE TABLE IF NOT EXISTS RELATIONSHIP_SIMULATION (
  CUSTOMER_NUMBER CHAR(10) PRIMARY KEY,
  SIMULATION_STAGE VARCHAR(20) NOT NULL
);
